[colors]

foreground = "#474747"
background = "#ffffff"
ansi = [
    "#ebebeb",
    "#d6000c",
    "#1d9700",
    "#c49700",
    "#0064e4",
    "#dd0f9d",
    "#00ad9c",
    "#878787",
]
brights = [
    "#cdcdcd",
    "#bf0000",
    "#008400",
    "#af8500",
    "#0054cf",
    "#c7008b",
    "#009a8a",
    "#282828",
]

cursor_fg = "#ffffff"
cursor_bg = "#282828"
cursor_border = "#282828"
compose_cursor = "#d04a00"

selection_fg = "none"
selection_bg = "rgba(205 205 205 62.5%)"

[colors.tab_bar]

background = "#ebebeb"

active_tab.fg_color = "#282828"
active_tab.bg_color = "#ffffff"

inactive_tab.fg_color = "#474747"
inactive_tab.bg_color = "#ebebeb"
inactive_tab_hover.fg_color = "#282828"
inactive_tab_hover.bg_color = "#cdcdcd"

new_tab.fg_color = "#474747"
new_tab.bg_color = "#ebebeb"
new_tab_hover.fg_color = "#282828"
new_tab_hover.bg_color = "#cdcdcd"
