[colors]

foreground = "#b9b9b9"
background = "#181818"
ansi = [
    "#252525",
    "#ed4a46",
    "#70b433",
    "#dbb32d",
    "#368aeb",
    "#eb6eb7",
    "#3fc5b7",
    "#777777",
]
brights = [
    "#3b3b3b",
    "#ff5e56",
    "#83c746",
    "#efc541",
    "#4f9cfe",
    "#ff81ca",
    "#56d8c9",
    "#dedede",
]

cursor_fg = "#181818"
cursor_bg = "#dedede"
cursor_border = "#dedede"
compose_cursor = "#e67f43"

selection_fg = "none"
selection_bg = "rgba(59 59 59 62.5%)"

[colors.tab_bar]

background = "#252525"

active_tab.fg_color = "#dedede"
active_tab.bg_color = "#181818"

inactive_tab.fg_color = "#b9b9b9"
inactive_tab.bg_color = "#252525"
inactive_tab_hover.fg_color = "#dedede"
inactive_tab_hover.bg_color = "#3b3b3b"

new_tab.fg_color = "#b9b9b9"
new_tab.bg_color = "#252525"
new_tab_hover.fg_color = "#dedede"
new_tab_hover.bg_color = "#3b3b3b"
